apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Description of flask
  annotations:
    github.com/project-slug: ${{values.organization + "/" + values.name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: ${{values.owner}}
  lifecycle: production
