apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-template
  description: all templates
spec:
  targets:
    - ./nodejs/template.yaml
    - ./flask/template.yaml
    - ./flask2/template.yaml
    